branches:
    only:
    - master

cache:
    directories:
    - ~/cache

sudo: required

language: csharp

services:
    - docker

before_install:
    - docker build -t webapp:test -f dockerfile/test .

script:
    - docker run -it --rm -v ~/publish:/root/publish -v ~/.nuget/packages:/root/nuget/packages webapp:test

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker build -t fredaso/webapp:autoLatest -f dockerfile/release .;
        docker login -u="$DOCKER_HUB_ID" -p="$DOCKER_HUB_PASSWORD";
        docker push fredaso/webapp:autoLatest;
        fi